
Vagrant.configure(2) do |config|
  config.vm.box = "yhli/centos-6.6"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.18.1.11"
  auto_config = false
  config.vm.provider "virtualbox" do |v|
    v.name = "test"
    v.memory = 1024
    v.cpus = 2
  end

  # config.vm.synced_folder "../data", "/vagrant_data"
end
